"""Bilingual rendering helpers (English + Traditional Chinese).

The digest vocabulary is bounded — regime labels, signal names, tactical levels,
recommendations, risk levels — so translation is a deterministic lookup, no LLM.
`lang` is "en" or "zh" (zh = 繁體中文). Unknown values fall back to the raw value.
"""
from __future__ import annotations

LANGS = ("en", "zh")

# --- static UI strings -----------------------------------------------------
S = {
    "title": {"en": "Investor Digest", "zh": "投資摘要"},
    "blk_market": {"en": "1. What changed in the market", "zh": "1. 市場變化"},
    "blk_book": {"en": "2. How your book should react", "zh": "2. 持倉應如何應對"},
    "blk_actions": {"en": "3. Action summary", "zh": "3. 行動摘要"},
    "macro_gate": {"en": "Macro gate", "zh": "宏觀風險閘"},
    "gauges": {"en": "Gauges", "zh": "指標"},
    "sp500": {"en": "S&P 500", "zh": "標普 500"},
    "ath": {"en": "ATH", "zh": "歷史高"},
    "from_high": {"en": "from high", "zh": "距高點"},
    "us_regime": {"en": "US regime", "zh": "美國市場狀態"},
    "strongest_signals": {"en": "Strongest signals", "zh": "最強訊號"},
    "us_indices": {"en": "US indices", "zh": "美國指數"},
    "hk_regime": {"en": "HK regime (proxy)", "zh": "港股市場狀態（估算）"},
    "hk_names": {"en": "HK names", "zh": "港股個股"},
    "confidence": {"en": "confidence", "zh": "信心"},
    "conf": {"en": "conf", "zh": "信心"},
    "breadth": {"en": "breadth", "zh": "廣度"},
    "as_of": {"en": "as of", "zh": "截至"},
    "context": {"en": "Context", "zh": "背景"},
    "macro": {"en": "macro", "zh": "宏觀"},
    "regime": {"en": "regime", "zh": "狀態"},
    "held": {"en": "held", "zh": "持有"},
    "watch": {"en": "watch", "zh": "觀察"},
    "last_analyzed": {"en": "last analyzed", "zh": "最近分析"},
    "no_prior": {"en": "no prior analysis", "zh": "尚無分析"},
    "px": {"en": "px", "zh": "價"},
    "no_action": {"en": "No actions required. Hold steady; monitor only.",
                  "zh": "無需行動，維持持倉，僅作觀察。"},
    "days": {"en": "d", "zh": "天"},
    "footer": {
        "en": "Generated by orchestrator. Reply with /us or /hk + a ticker for a fresh deep-dive.",
        "zh": "由編排器生成。回覆 /us 或 /hk 加股票代號即可獲得即時深入分析。",
    },
    "tactical": {"en": "tactical", "zh": "戰術"},
    "recommendation": {"en": "recommendation", "zh": "建議"},
    "hold_monitor": {"en": "hold / monitor", "zh": "持有／觀察"},
    "escalated_from": {"en": "escalated from", "zh": "由…升級"},
    "entry_blocked": {"en": "entry blocked", "zh": "暫緩進場"},
    "was": {"en": "was", "zh": "原為"},
    "calm": {"en": "calm", "zh": "平穩"},
    "macro_risk": {"en": "macro risk", "zh": "宏觀風險"},
    "act": {"en": "Act", "zh": "行動"},
}

# --- bounded vocabularies --------------------------------------------------
REGIME = {
    "Risk-On Expansion": {"en": "Risk-On Expansion", "zh": "風險偏好擴張"},
    "Late-Cycle Inflation": {"en": "Late-Cycle Inflation", "zh": "週期晚期通脹"},
    "Risk-Off Defensive": {"en": "Risk-Off Defensive", "zh": "避險防禦"},
    "Deflationary Shock": {"en": "Deflationary Shock", "zh": "通縮衝擊"},
    "Regime Uncertain": {"en": "Regime Uncertain", "zh": "狀態不明"},
    # HK proxy labels
    "Risk-On": {"en": "Risk-On", "zh": "風險偏好"},
    "Risk-Off": {"en": "Risk-Off", "zh": "避險"},
    "Mixed": {"en": "Mixed", "zh": "中性混合"},
    "Uncertain": {"en": "Uncertain", "zh": "不明"},
}
SIGNAL = {
    "relative_strength": {"en": "relative_strength", "zh": "相對強度"},
    "relative_volume": {"en": "relative_volume", "zh": "相對成交量"},
    "capital_rotation": {"en": "capital_rotation", "zh": "資金輪動"},
    "risk_on_off": {"en": "risk_on_off", "zh": "風險偏好/避險"},
    "inflation": {"en": "inflation", "zh": "通脹"},
    "growth": {"en": "growth", "zh": "增長"},
    "recession": {"en": "recession", "zh": "衰退"},
    "liquidity": {"en": "liquidity", "zh": "流動性"},
}
TACTICAL = {
    "": {"en": "hold / monitor", "zh": "持有／觀察"},
    "YELLOW_WATCH": {"en": "YELLOW_WATCH", "zh": "黃色觀察"},
    "ORANGE_TRIM": {"en": "ORANGE_TRIM", "zh": "橙色減持"},
    "RED_DEFENSIVE": {"en": "RED_DEFENSIVE", "zh": "紅色防禦"},
    "BLACK_EXIT": {"en": "BLACK_EXIT", "zh": "黑色清倉"},
}
RECO = {
    "BUY_NOW": {"en": "BUY_NOW", "zh": "立即買入"},
    "WAIT_FOR_PRICE": {"en": "WAIT_FOR_PRICE", "zh": "等待價格"},
    "PASS": {"en": "PASS", "zh": "略過"},
    "HOLD_OFF": {"en": "HOLD_OFF", "zh": "暫緩買入"},
}
RISK_LEVEL = {
    "LOW": {"en": "LOW", "zh": "低"},
    "MEDIUM": {"en": "MEDIUM", "zh": "中"},
    "HIGH": {"en": "HIGH", "zh": "高"},
    "CRITICAL": {"en": "CRITICAL", "zh": "危急"},
}
LIGHT = {
    "Red": {"en": "Red", "zh": "紅"},
    "Yellow": {"en": "Yellow", "zh": "黃"},
    "Green": {"en": "Green", "zh": "綠"},
}
GAUGE_LABEL = {
    "vix": {"en": "VIX", "zh": "VIX"},
    "fear_greed": {"en": "Fear&Greed", "zh": "恐懼與貪婪"},
    "cape": {"en": "CAPE", "zh": "CAPE"},
    "yield_curve": {"en": "10Y-2Y", "zh": "10Y-2Y"},
    "hy_oas": {"en": "HY OAS", "zh": "高收益利差"},
}
# Macro action band: match by leading keyword from risk_analysis' action string.
MACRO_ACTION = {
    "HOLD": {"en": None, "zh": "持有 — 不部署現金，不追高。"},
    "PREPARE": {"en": None, "zh": "準備現金 — 留意機會。"},
    "DEPLOY ALL": {"en": None, "zh": "部署全部剩餘現金。"},
    "DEPLOY": {"en": None, "zh": "分批部署現金。"},
}


def t(key: str, lang: str) -> str:
    return S.get(key, {}).get(lang, S.get(key, {}).get("en", key))


def _lookup(table: dict, value, lang: str):
    entry = table.get(value if value is not None else "")
    if entry:
        return entry.get(lang, entry.get("en"))
    return value


def regime(label, lang):      return _lookup(REGIME, label, lang)
def signal_name(name, lang):  return _lookup(SIGNAL, name, lang)
def tactical(label, lang):    return _lookup(TACTICAL, label or "", lang)
def reco(code, lang):         return _lookup(RECO, code, lang)
def risk_level(level, lang):  return _lookup(RISK_LEVEL, level, lang)
def light(color, lang):       return _lookup(LIGHT, color, lang)
def gauge_label(key, lang):   return GAUGE_LABEL.get(key, {}).get(lang, key)


def macro_action(action_text: str | None, lang: str) -> str:
    """Localize the macro action band. EN keeps the original; ZH maps by keyword."""
    if not action_text:
        return ""
    if lang == "en":
        return action_text
    up = action_text.upper()
    for prefix in ("DEPLOY ALL", "DEPLOY", "PREPARE", "HOLD"):
        if up.startswith(prefix):
            return MACRO_ACTION[prefix]["zh"]
    return action_text  # unknown band: leave as-is
