"""LLM-driven Section 12 narrative generation (DeepSeek by default).

When `DEEPSEEK_API_KEY` is set, `llm_interpret()` returns a dict matching the
rule-based `interpret()` shape, but with claims generated by analysis of the
full signal/regime/breadth/changed-since context.

Anti-hallucination policy from §4.5 is enforced in the system prompt:
  - Only hedge verbs: appears, suggests, may indicate, consistent with.
  - No causality, no certainty, no exact-flow claims.
  - Every claim cites supporting + conflicting evidence from the actual data.
  - Tickers come from a fixed whitelist; the LLM cannot invent symbols.
  - Validation-failed signals are tagged so the LLM down-weights them.

On any failure (no key, HTTP error, malformed response, invalid JSON, schema
violation, hallucinated ticker), the caller falls back to rule-based
`interpret()`. The LLM is a sharpener, not a load-bearing dependency.
"""
from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from dataclasses import asdict
from typing import Any

import pandas as pd

from .interpret import CONFIDENCE_FLOOR

log = logging.getLogger(__name__)


DEEPSEEK_URL = "https://api.deepseek.com/chat/completions"
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")
DEEPSEEK_TIMEOUT_S = float(os.environ.get("DEEPSEEK_TIMEOUT_S", "45"))


SYSTEM_PROMPT = """You are a Senior Quantitative Researcher writing the "Potential Explanations" section of a Capital Rotation Monitoring System's daily report.

Your job: analyze the day's signal snapshot and produce 0 to 3 narrative claims explaining what the data is consistent with. Quality over quantity. If signals are genuinely inconclusive, return zero claims rather than weak ones.

NON-NEGOTIABLE RULES:

1. HEDGED LANGUAGE ONLY. Every claim text must use one of: "appears", "suggests", "may indicate", "consistent with", "tentatively consistent with". NEVER say "is", "will", "definitely", "certainly", "guarantees", "proves".

2. NO CAUSALITY, NO EXACT FLOWS. You are reading market-implied signals, not measuring money. Phrase claims as "consistent with rotation toward X" not "money is moving to X".

3. SUPPORTING + CONFLICTING EVIDENCE FOR EVERY CLAIM. Each claim's "supporting" array must cite specific numbers from the provided data (e.g. "Risk-On/Off: -68.1 (conf 0.58)"). Each "conflicting" array must list the strongest evidence against the claim (or note "no strong conflict observed" if none).

4. TICKER WHITELIST. Only reference symbols that appear in the provided universe list. Do NOT invent or guess tickers.

5. RESPECT VALIDATION STATUS. Signals tagged validated=false should carry LESS weight in your reasoning; mention in "conflicting" that their predictive power has not been demonstrated.

6. CONFIDENCE NUMERIC. Each claim's confidence (0.0 to 1.0) must reflect the consistency of the supporting evidence. Suppress narratives where confidence would be below 0.35.

7. JSON OUTPUT ONLY. No prose before or after.

OUTPUT SCHEMA (strict):

{
  "claims": [
    {
      "narrative_id": "snake_case_id (e.g. risk_off_rotation, growth_acceleration)",
      "text": "One or two hedged sentences naming what the data is consistent with.",
      "confidence": 0.0,
      "supporting": ["Risk-On/Off: -68.1 (conf 0.58)", "Capital Rotation: -23.1"],
      "conflicting": ["Growth-leaders SMH r_w -5.8% is consistent with the claim, NOT against it" or "No strong contradicting signal observed"],
      "implicated_strengthening": ["TLT", "GLD"],
      "implicated_weakening": ["SPY", "QQQ"],
      "reasoning": "One sentence on the chain of reasoning, for the audit log (not shown in the public report)."
    }
  ],
  "cross_signal_conflicts": [
    "Plain-language description of any pair of signals that point in contradictory directions."
  ]
}

If signals are inconclusive: {"claims": [], "cross_signal_conflicts": ["..."]}.
"""


def _have_key() -> bool:
    return bool(os.environ.get("DEEPSEEK_API_KEY"))


def _format_signals_block(signals: dict[str, dict], verdicts: dict | None) -> str:
    """Pretty-print signal snapshot + validation status, one signal per line."""
    lines = []
    for name in ("relative_strength", "relative_volume", "capital_rotation",
                 "risk_on_off", "inflation", "growth", "recession", "liquidity"):
        s = signals.get(name, {})
        score = s.get("score")
        conf = s.get("confidence")
        v = verdicts.get(name) if verdicts else None
        if score is None:
            score_str = "—"
        else:
            score_str = f"{score:+.1f}"
        conf_str = f"conf {conf:.2f}" if conf is not None else "conf —"
        if v is None:
            val_str = "validation: not run"
        else:
            val_str = f"validation: {v.verdict}"
            if v.verdict == "fail" and v.reason:
                val_str += f" ({v.reason})"
        lines.append(f"  - {name}: {score_str} ({conf_str}); {val_str}")
    return "\n".join(lines)


def _format_metrics_block(metrics: pd.DataFrame, top_n: int = 6) -> str:
    """Top movers (strong + weak) and volume anomalies."""
    if metrics is None or metrics.empty:
        return "  (no metrics available)"
    top = metrics.dropna(subset=["r_w"]).sort_values("r_w", ascending=False).head(top_n)
    bot = metrics.dropna(subset=["r_w"]).sort_values("r_w").head(top_n)
    vol_anom = metrics.dropna(subset=["vz"])
    vol_anom = vol_anom[vol_anom["vz"].abs() >= 2.0].sort_values("vz", ascending=False).head(top_n)

    lines = []
    lines.append("Top strengthening (by r_w):")
    for _, r in top.iterrows():
        lines.append(f"  - {r['symbol']}: r_w {r['r_w']*100:+.2f}%  r_d {r['r_d']*100:+.2f}%")
    lines.append("Top weakening (by r_w):")
    for _, r in bot.iterrows():
        lines.append(f"  - {r['symbol']}: r_w {r['r_w']*100:+.2f}%  r_d {r['r_d']*100:+.2f}%")
    if not vol_anom.empty:
        lines.append("Volume anomalies (|log-V z-score| ≥ 2):")
        for _, r in vol_anom.iterrows():
            lines.append(f"  - {r['symbol']}: vz {r['vz']:+.1f}  r_d {r['r_d']*100:+.2f}%")
    return "\n".join(lines)


def _format_deltas(label: str, now: dict[str, dict], prev: dict[str, dict] | None) -> str:
    if not prev:
        return f"{label}: no prior snapshot"
    diffs = []
    SKIP = {"relative_strength"}  # per-asset signal; delta is meaningless
    for name, n in now.items():
        if name in SKIP or n.get("score") is None:
            continue
        p = prev.get(name, {})
        if p.get("score") is None:
            continue
        d = n["score"] - p["score"]
        diffs.append((name, n["score"], d))
    diffs.sort(key=lambda x: abs(x[2]), reverse=True)
    diffs = diffs[:5]
    if not diffs:
        return f"{label}: no measurable change"
    parts = [f"{name} now {score:+.1f} (Δ {d:+.1f})" for name, score, d in diffs]
    return f"{label}: " + "; ".join(parts)


def _build_user_prompt(
    asof,
    signals: dict[str, dict],
    metrics: pd.DataFrame,
    regime: dict | None,
    verdicts: dict | None,
    prev_d: dict | None,
    prev_w: dict | None,
    prev_m: dict | None,
    universe: list[str],
) -> str:
    regime_line = "Regime: not yet classified"
    if regime:
        regime_line = (
            f"Regime: {regime['regime']}"
            + (f" (was {regime['prev_regime']})" if regime.get("prev_regime") else "")
            + (f" — day {regime['days_in_regime']} in regime" if regime.get("days_in_regime") else "")
            + (f" — confidence {regime['confidence']:.2f}" if regime.get("confidence") is not None else "")
        )

    return f"""Date (asof): {asof}

{regime_line}

8 Composite Signals (score range [-100, +100] except RelVol/Liquidity which are 0-100):
{_format_signals_block(signals, verdicts)}

Per-asset Metrics:
{_format_metrics_block(metrics)}

Period-over-period changes:
{_format_deltas("Vs yesterday", signals, prev_d)}
{_format_deltas("Vs last week", signals, prev_w)}
{_format_deltas("Vs last month", signals, prev_m)}

Universe whitelist (only reference these symbols):
{', '.join(sorted(universe))}

Produce the Section 12 JSON.
"""


def _call_deepseek(prompt: str) -> dict | None:
    """POST to DeepSeek. Returns parsed JSON dict or None on failure."""
    key = os.environ.get("DEEPSEEK_API_KEY")
    if not key:
        return None
    body = json.dumps({
        "model": DEEPSEEK_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.2,  # low; we want consistent hedged language
        "max_tokens": 1500,
    }).encode()
    req = urllib.request.Request(
        DEEPSEEK_URL, data=body,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=DEEPSEEK_TIMEOUT_S) as resp:
            data = json.loads(resp.read())
    except (urllib.error.URLError, TimeoutError) as exc:
        log.warning("DeepSeek network error: %s", exc); return None
    except json.JSONDecodeError as exc:
        log.warning("DeepSeek response not JSON: %s", exc); return None

    try:
        content = data["choices"][0]["message"]["content"]
        usage = data.get("usage", {})
        parsed = json.loads(content)
        parsed["_meta"] = {
            "model": data.get("model", DEEPSEEK_MODEL),
            "input_tokens": usage.get("prompt_tokens"),
            "output_tokens": usage.get("completion_tokens"),
        }
        return parsed
    except (KeyError, IndexError, json.JSONDecodeError) as exc:
        log.warning("DeepSeek payload unparseable: %s; raw: %s", exc, str(data)[:400])
        return None


# ============================================================
# Validation of LLM output
# ============================================================

_REQUIRED_CLAIM_KEYS = {"narrative_id", "text", "confidence",
                         "supporting", "conflicting",
                         "implicated_strengthening", "implicated_weakening"}


def _validate_and_sanitize(
    parsed: dict,
    universe: list[str],
) -> dict | None:
    """Reject malformed responses; strip tickers not in universe; drop claims
    that violate the hedge-verb rule. Returns sanitized dict or None."""
    if not isinstance(parsed, dict):
        log.warning("LLM output is not a dict"); return None
    claims = parsed.get("claims", [])
    if not isinstance(claims, list):
        log.warning("LLM 'claims' not a list"); return None

    universe_set = set(universe)
    sanitized_claims = []
    FORBIDDEN_WORDS = {"will", "definitely", "certainly", "guarantees",
                       "proves", "always", "never doubt"}
    HEDGE_VERBS = ("appears", "suggests", "may indicate", "may suggest",
                   "consistent with", "tentatively consistent",
                   "appears to", "is consistent")

    for c in claims:
        if not isinstance(c, dict):
            continue
        missing = _REQUIRED_CLAIM_KEYS - set(c.keys())
        if missing:
            log.info("LLM claim missing keys %s; dropping", missing); continue
        try:
            conf = float(c["confidence"])
        except (TypeError, ValueError):
            log.info("LLM claim non-numeric confidence; dropping"); continue
        if not (0.0 <= conf <= 1.0):
            log.info("LLM claim confidence %s out of range; dropping", conf); continue
        if conf < CONFIDENCE_FLOOR:
            continue  # below-floor narratives suppressed by §4.5

        text = str(c["text"]).strip()
        text_lower = text.lower()
        if not any(v in text_lower for v in HEDGE_VERBS):
            log.info("LLM claim lacks hedge verb; dropping: %r", text); continue
        if any(word in text_lower.split() for word in FORBIDDEN_WORDS):
            log.info("LLM claim uses forbidden word; dropping: %r", text); continue

        # Whitelist tickers
        strengthening = [t for t in c["implicated_strengthening"] if t in universe_set]
        weakening = [t for t in c["implicated_weakening"] if t in universe_set]
        dropped = (set(c["implicated_strengthening"]) | set(c["implicated_weakening"])) - universe_set
        if dropped:
            log.info("LLM hallucinated tickers dropped: %s", dropped)

        supporting = c["supporting"] if isinstance(c["supporting"], list) else []
        conflicting = c["conflicting"] if isinstance(c["conflicting"], list) else []

        sanitized_claims.append({
            "narrative_id": str(c["narrative_id"]),
            "text": text,
            "confidence": conf,
            "bucket": "high" if conf >= 0.70 else "medium" if conf >= 0.50 else "low",
            "supporting": [str(s) for s in supporting][:8],
            "conflicting": [str(s) for s in conflicting][:8],
            "implicated_strengthening": strengthening[:20],
            "implicated_weakening": weakening[:20],
            "tags": ["llm"],
            "reasoning": str(c.get("reasoning", "")),
        })

    cross = parsed.get("cross_signal_conflicts", [])
    if not isinstance(cross, list):
        cross = []
    cross = [str(x) for x in cross][:5]

    return {
        "claims": sanitized_claims,
        "cross_signal_conflicts": cross,
        "_meta": parsed.get("_meta", {}),
    }


# ============================================================
# Public entry
# ============================================================

def llm_interpret(
    asof,
    signals: dict[str, dict],
    metrics: pd.DataFrame,
    regime: dict | None = None,
    verdicts: dict | None = None,
    prev_d_signals: dict | None = None,
    prev_w_signals: dict | None = None,
    prev_m_signals: dict | None = None,
    universe: list[str] | None = None,
) -> dict | None:
    """Returns LLM-generated Section 12 dict, or None on any failure.

    Caller is responsible for falling back to rule-based interpret(); this
    function never raises and never silently degrades into a stub.
    """
    if not _have_key():
        return None
    if universe is None:
        # Reasonable default — anything we typically track
        universe = ["SPY","QQQ","IWM","EZU","EEM","EWJ","GLD","SLV","TLT","UUP",
                    "FXF","CPER","USO","SMH","XLI","IYT","BTC-USD","ETH-USD",
                    "IEF","HYG","LQD","XLK","XLF","XLE","XLV","XLY","XLP",
                    "XLU","XLB","XLRE","XLC","^MOVE"]

    prompt = _build_user_prompt(
        asof=asof, signals=signals, metrics=metrics, regime=regime,
        verdicts=verdicts, prev_d=prev_d_signals, prev_w=prev_w_signals,
        prev_m=prev_m_signals, universe=universe,
    )
    raw = _call_deepseek(prompt)
    if raw is None:
        return None
    sanitized = _validate_and_sanitize(raw, universe)
    if sanitized is None:
        return None
    sanitized["source"] = "deepseek-llm"
    return sanitized
